### ISSUE TITLE
Unable to choose

### ISSUE THREAD

**Issue by Thubs** [arcolinuxd/arco-gnome#1]
This isn't a problem about this DE but I couldn't find a repository for your installer so I put it in here.
 I am unable to chose which DE/WM I want to install, this could be user error but I've tried it 3 times now and it's given the same DE/WM every time even though I chose 3 WM's and 2 DE's I got 13 of both 2 of which were what I wanted but I was also missing the other ones which I also wanted. Other than this problem I love the installer and it runs really well.

**Comment by arcolinuxz** [comment]
https://arcolinuxforum.com

that is where this should go
